services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27016:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - metcs602-hw4-network
  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - "27018:8081"
    environment:
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - metcs602-hw4-network
  
networks:
  metcs602-hw4-network:
    driver: bridge